version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "voting-app/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "voting-result/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "voting-worker/"
    schedule:
      interval: "weekly"            
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"