apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-worker-deploy
  labels:
    name: voting-worker-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-worker-pod
      app: demo-voting-app
  template:
    metadata:
      name: voting-worker-pod
      labels:
        name: voting-worker-pod
        app: demo-voting-app
    spec:
      containers:
        - name: voting-worker-pod
          image: rotoku/voting-worker:v1