apiVersion: v1
kind: Pod
metadata:
  name: voting-worker-pod
  labels:
    name: voting-worker-pod
    app: demo-voting-app
spec:
  containers:
    - name: voting-worker-pod
      image: rotoku/voting-worker:v1