apiVersion: v1
kind: Service
metadata:
  name: voting-result-service
  labels:
    name: voting-result-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    name: voting-result-pod
    app: demo-voting-app